// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable} antialiased
          min-h-screen w-full
          bg-gradient-to-br from-blue-100 via-white to-green-100
          relative
        `}
        style={{
          margin: 0,
          padding: 0,
        }}
      >
        {/* SVG Pattern Background */}
        <svg
          className="fixed inset-0 w-full h-full pointer-events-none"
          style={{ zIndex: 0 }}
          aria-hidden="true"
          preserveAspectRatio="none"
        >
          <defs>
            <pattern id="bubbles" x="0" y="0" width="120" height="120" patternUnits="userSpaceOnUse">
              <circle cx="30" cy="30" r="2" fill="#a5b4fc" opacity="0.2" />
              <circle cx="90" cy="90" r="3" fill="#6ee7b7" opacity="0.15" />
              <circle cx="60" cy="60" r="1.5" fill="#fca5a5" opacity="0.18" />
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#bubbles)" />
        </svg>
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
